# Generated by Django 2.2.2 on 2020-03-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', 'Sale'), ('2', 'Limited'), ('3', 'Extreme Sale')], default='', max_length=2),
        ),
    ]
