# Generated by Django 2.2.2 on 2019-12-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_email',
        ),
    ]
