# Generated by Django 4.0 on 2021-12-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='core.Coupon'),
        ),
    ]
