# Generated by Django 2.2.2 on 2020-03-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200327_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='additional_info',
            field=models.TextField(default='', verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Sale'), ('2', 'Limited'), ('3', 'Extreme Sale')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Discounted Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_sub_one',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sub Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_sub_three',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sub Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_sub_two',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sub Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='', max_length=1, verbose_name='Labeled Color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', help_text='This text will be used in url. Please use following format: Item-Name-Tag', verbose_name='Item Tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
    ]
