# Generated by Django 2.2.2 on 2020-03-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200327_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Main Image'),
        ),
    ]
