# Generated by Django 2.2.2 on 2020-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200327_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_sub_one',
            field=models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_sub_three',
            field=models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_sub_two',
            field=models.ImageField(default='default.png', upload_to='item_pics', verbose_name='Sub Image'),
        ),
    ]
