# Generated by Django 2.2.2 on 2020-06-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200328_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Sale'), ('2', 'Limited'), ('3', 'ExtremeSale')], max_length=2, null=True),
        ),
    ]
